### ISSUE TITLE
In Xamarin.iOS 13.2 with iOs13.1 version mail subject not displayed. 

### ISSUE THREAD

**Issue by SU354872** [xamarin/bugzilla-archives#1]
Hi,

In our project we are attaching a report and writing a message in mail body.
When we are sending mail, we are using Outlook.
When AirDrop opens, Iam selecting "Copy to Outlook" option.

- Then I have to get attachment and message in mail body.
- But only attachment is seen, message in mail body is empty.
- This issue is not observed in older versions of Xamarin and iOS 12.x
- This issue is only seen in Xamarin.iOS 13.2 with iOS13.x version 

- And also observed, whatever message iam passing it is seen in AirDrop text.
- Not in mail body.
-Can you please help me to fix this issue.
- Attached Sample project, images.

Steps to use sample app:
1. Click on "Sendto" button"
2. observe message "Hello world" message shown in airdrop,
3. Click on copy to outlook option which opens mail with attachment, with no message in mail body.
4. Fix required: both attachment and "HelloWorld" message should be seen in mail when we click "Copy to Outlook" button. 

Thanks.
[SendToSampleApp (2).zip](https://github.com/xamarin/bugzilla-archives/files/3686357/SendToSampleApp.2.zip)
![Email_not having message body](https://user-images.githubusercontent.com/56119741/66132439-b01cfb80-e612-11e9-9835-94e4f4996baf.png)
![Message showing in airdrop](https://user-images.githubusercontent.com/56119741/66132452-b7440980-e612-11e9-9307-115e1a445ec8.png)

**Comment by akoeplinger** [comment]
This is an archive repository for the old Xamarin Bugzilla and is read-only.

Please file an issue on the respective GitHub projects like https://github.com/xamarin/xamarin-android or https://github.com/xamarin/xamarin-macios instead.
