### ISSUE TITLE
Data removal

### ISSUE THREAD

**Issue by luttje** [xamarin/bugzilla-archives#10]
Hi there!

I'm an EU citizen and was wondering if you could help me by please removing my name and username from the following bug I reported: https://xamarin.github.io/bugzilla-archives/59/59946/bug.html

The lines I found: 
* https://github.com/xamarin/bugzilla-archives/blob/bd733f634ac896165feffaafc35599c915c59022/59/59946/bug.html#L387
* https://github.com/xamarin/bugzilla-archives/blob/bd733f634ac896165feffaafc35599c915c59022/59/59946/bug.html#L416
* https://github.com/xamarin/bugzilla-archives/blob/bd733f634ac896165feffaafc35599c915c59022/59/59946/bug.html#L575
* https://github.com/xamarin/bugzilla-archives/blob/bd733f634ac896165feffaafc35599c915c59022/59/59946/bug.html#L640

* https://github.com/xamarin/bugzilla-archives/blob/bd733f634ac896165feffaafc35599c915c59022/59/59946/activity.html#L249
* https://github.com/xamarin/bugzilla-archives/blob/bd733f634ac896165feffaafc35599c915c59022/59/59946/activity.html#L256

Thanks in advance!

**Comment by akoeplinger** [comment]
Done!

**Comment by luttje** [comment]
Thanks for the swift handling. Much appreciated! Could you remove this issue as well? Thanks 😊

Have a nice day

**Comment by luttje** [comment]
Hmm now that I think about it, my personal data is still in the git history, visible with your commit.

Can I ask you to rewrite the git history so as to remove my data completely? 

Sorry for the bother

**Comment by akoeplinger** [comment]
Good point thanks, I've rebased the commit out of git history now. I'll delete this issue now.
