### ISSUE TITLE
Bugzilla Archive attachment availability?

### ISSUE THREAD

**Issue by katiska** [xamarin/bugzilla-archives#11]
Are the attachments from the Bugzilla Archive available for viewing somewhere? I'm getting "Page not found." error when following the links in the Xamarin Bugzilla archive.

I'm specifically interested in the attachments of bug [#55721](https://bugzilla.xamarin.com/55/55721/bug.html): ["Memory leak fix"](https://bugzilla.xamarin.com/attachment.cgi?id=22331&file=HttpConnection.patch) and ["test case"](https://bugzilla.xamarin.com/attachment.cgi?id=21876&file=test.zip).

**Comment by akoeplinger** [comment]
Fixed now, thanks for the report!

**Comment by katiska** [comment]
Thanks!
