### ISSUE TITLE
Failed to compile the generated registrar code. Please file a bug report at http://bugzilla.xamarin.com (MT4109) 

### ISSUE THREAD

**Issue by thodupuzhakkaran** [xamarin/bugzilla-archives#3]
Using visual studio community for mac.
Version 7.7.1(build 15)
 Xcode version-11
Another error which I am getting with this error- Error GEA45E82A: expected identifier or '{' (GEA45E82A) .

**Comment by akoeplinger** [comment]
This is an archive repository for the old Xamarin Bugzilla and is read-only.

Please file an issue on the respective GitHub projects like https://github.com/xamarin/xamarin-android or https://github.com/xamarin/xamarin-macios instead.
