### ISSUE TITLE
MT0099 Internal Error : Interpreter is currently only available for 64 bits

### ISSUE THREAD

**Issue by alaskanrogue** [xamarin/bugzilla-archives#6]
Using VS 2019 Mac Pre, which was updated this morning along with Xcode and Mono, working with a Xamarin solution which was buildable using the latest VS 2019 Win Pre v16.7.0 Preview 1 and using a simulator, encountering the following error:

![3](https://user-images.githubusercontent.com/14001196/82590460-b7762280-9b6b-11ea-8cda-903f67550623.png)

The target device is an iPhone 5, which is 32 bit, but specified in the project settings. The solution has been built successfully in the past.

**Comment by akoeplinger** [comment]
This is an archive repository for the old Xamarin Bugzilla and is read-only.

Please file an issue on the respective GitHub projects like https://github.com/xamarin/xamarin-android or https://github.com/xamarin/xamarin-macios instead.
